name: actions

on: 
  pull_request: 
    types: [closed, assigned, opened, reopened]
jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: list-files
        run: |
          pwd 
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHHUB_WORKSPACE
          echo
      - name: checkout
        uses: actions/checkout@v1
      - name: list-files-after-checkout
        run: | 
          pwd
          ls
      - name: simple-js-actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: jeromehaas
      - name: log-greeting-name
        run: echo "${{ steps.greet.outputs.time }}"


